src/beans/Message.java
package beans;

import java.io.Serializable;
import java.util.Date;

public class Message implements Serializable {

	private int id;
    private String title;
    private String text;
    private String category;
    private int userId;
    private Date createdDate;
    private Date updatedDate;
	public int getId() {
		return id;
	}
	public void setId(int id) {
		this.id = id;
	}
	public String getTitle() {
		return title;
	}
	public void setTitle(String title) {
		this.title = title;
	}
	public String getText() {
		return text;
	}
	public void setText(String text) {
		this.text = text;
	}
	public String getCategory() {
		return category;
	}
	public void setCategory(String category) {
		this.category = category;
	}
	public int getUserId() {
		return userId;
	}
	public void setUserId(int userId) {
		this.userId = userId;
	}
	public Date getCreatedDate() {
		return createdDate;
	}
	public void setCreatedDate(Date createdDate) {
		this.createdDate = createdDate;
	}
	public Date getUpdatedDate() {
		return updatedDate;
	}
	public void setUpdatedDate(Date updatedDate) {
		this.updatedDate = updatedDate;
	}
}

src/beans/UserComment.java
package beans;

import java.io.Serializable;
import java.util.Date;

public class UserComment implements Serializable {

	private int id;
	private String text;
    private int userId;
    private int messageId;
    private String name;
    private Date createdDate;
    private Date updatedDate;

	public int getId() {
		return id;
	}
	public void setId(int id) {
		this.id = id;
	}
	public String getText() {
		return text;
	}
	public void setText(String text) {
		this.text = text;
	}
	public int getUserId() {
		return userId;
	}
	public void setUserId(int userId) {
		this.userId = userId;
	}
	public int getMessageId() {
		return messageId;
	}
	public void setMessageId(int messageId) {
		this.messageId = messageId;
	}
	public String getName() {
		return name;
	}
	public void setName(String name) {
		this.name = name;
	}
	public Date getCreatedDate() {
		return createdDate;
	}
	public void setCreatedDate(Date createdDate) {
		this.createdDate = createdDate;
	}
	public Date getUpdatedDate() {
		return updatedDate;
	}
	public void setUpdatedDate(Date updatedDate) {
		this.updatedDate = updatedDate;
	}
	public String[] getSplitedText() {
        return text.split("\r\n");
    }
}

src/controller/HomeServlet.java
package controller;

import java.io.IOException;
import java.util.List;

import javax.servlet.ServletException;
import javax.servlet.annotation.WebServlet;
import javax.servlet.http.HttpServlet;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;

import beans.UserComment;
import beans.UserMessage;
import service.CommentService;
import service.MessageService;

@WebServlet(urlPatterns = { "/index.jsp" })
public class HomeServlet extends HttpServlet {

	@Override
    protected void doGet(HttpServletRequest request, HttpServletResponse response)
            throws IOException, ServletException {

		String start = request.getParameter("start");
		String end = request.getParameter("end");
		String category = request.getParameter("category");

		request.setAttribute("start", start);
		request.setAttribute("end", end);
		request.setAttribute("category", category);

		//メッセージ取得
		List<UserMessage> messages = new MessageService().select(start, end, category);

		/*UserMessage message = messages.get(0);
		String[] splitText = message.getSplitedText();
		System.out.println("出力します");
		for (String oneLine : splitText) {
			System.out.println(oneLine);
		}*/

		//メッセージをリクエストにセット
        request.setAttribute("messages", messages);

        //コメント取得
  		List<UserComment> comments = new CommentService().select();
  		//コメントをリクエストにセット
        request.setAttribute("comments", comments);

        request.getRequestDispatcher("/home.jsp").forward(request, response);
    }
}

src/controller/LoginServlet.java
package controller;

import java.io.IOException;
import java.util.ArrayList;
import java.util.List;

import javax.servlet.ServletException;
import javax.servlet.annotation.WebServlet;
import javax.servlet.http.HttpServlet;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import javax.servlet.http.HttpSession;

import org.apache.commons.lang.StringUtils;

import beans.User;
import service.UserService;

@WebServlet(urlPatterns = { "/login" })
public class LoginServlet extends HttpServlet {

	@Override
    protected void doGet(HttpServletRequest request, HttpServletResponse response)
            throws IOException, ServletException {

        request.getRequestDispatcher("login.jsp").forward(request, response);
    }

	@Override
    protected void doPost(HttpServletRequest request, HttpServletResponse response)
            throws IOException, ServletException {

		List<String> errorMessages = new ArrayList<String>();

        String account = request.getParameter("account");
        String password = request.getParameter("password");

        User user = new UserService().select(account, password);
        if (! isValid(account, password, user, errorMessages)) {
        	request.setAttribute("errorMessages", errorMessages);
        	request.setAttribute("account", account);
            request.getRequestDispatcher("login.jsp").forward(request, response);
            return;
        }

        HttpSession session = request.getSession();
        session.setAttribute("loginUser", user);
        response.sendRedirect("./");
    }

	private boolean isValid(String account, String password, User user, List<String> errorMessages) {

        if ((user == null) && (StringUtils.isEmpty(account))) {
        	errorMessages.add("アカウントが入力されていません");
        }

        if ((user == null) && (StringUtils.isEmpty(password))) {
        	errorMessages.add("パスワードが入力されていません");
        }

        if ((user == null) && (! StringUtils.isEmpty(password)) && (! StringUtils.isEmpty(account))) {
        	errorMessages.add("アカウントまたはパスワードが誤っています");
        }

        if (errorMessages.size() == 0) {
            return true;
        }
        return false;
    }
}

src/controller/ManagementServlet.java
package controller;

import java.io.IOException;
import java.util.List;

import javax.servlet.ServletException;
import javax.servlet.annotation.WebServlet;
import javax.servlet.http.HttpServlet;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;

import beans.UserBranchDepartment;
import service.UserService;

@WebServlet(urlPatterns = { "/management" })
public class ManagementServlet extends HttpServlet {

	@Override
    protected void doGet(HttpServletRequest request, HttpServletResponse response)
            throws IOException, ServletException{

		//ユーザー情報取得
		List<UserBranchDepartment> userInformations = new UserService().select();
		//ユーザー情報をリクエストにセット
        request.setAttribute("userInformations", userInformations);

		request.getRequestDispatcher("/management.jsp").forward(request, response);
	}
}

src/controller/MessageServlet.java
package controller;

import java.io.IOException;
import java.util.ArrayList;
import java.util.List;

import javax.servlet.ServletException;
import javax.servlet.annotation.WebServlet;
import javax.servlet.http.HttpServlet;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import javax.servlet.http.HttpSession;

import org.apache.commons.lang.StringUtils;

import beans.Message;
import beans.User;
import service.MessageService;

@WebServlet(urlPatterns = { "/message" })
public class MessageServlet extends HttpServlet {

	@Override
    protected void doGet(HttpServletRequest request, HttpServletResponse response)
            throws IOException, ServletException {

        request.getRequestDispatcher("message.jsp").forward(request, response);
    }

	@Override
    protected void doPost(HttpServletRequest request, HttpServletResponse response)
            throws IOException, ServletException {

        HttpSession session = request.getSession();
        List<String> errorMessages = new ArrayList<String>();

        Message message = getMessage(request);
        if (!isValid(message, errorMessages)) {
        	request.setAttribute("errorMessages", errorMessages);
            String title = message.getTitle();
        	String category = message.getCategory();
        	String text = message.getText();
        	request.setAttribute("title", title);
        	request.setAttribute("category", category);
        	request.setAttribute("text", text);
        	request.getRequestDispatcher("message.jsp").forward(request, response);
            return;
        }

        User user = (User) session.getAttribute("loginUser");
        message.setUserId(user.getId());

        new MessageService().insert(message);
        response.sendRedirect("./");
    }

	private Message getMessage(HttpServletRequest request) throws IOException, ServletException{

		Message message = new Message();
		message.setTitle(request.getParameter("title"));
		message.setCategory(request.getParameter("category"));
		message.setText(request.getParameter("text"));
		return message;
	}

    private boolean isValid(Message message, List<String> errorMessages) {

    	String title = message.getTitle();
    	String category = message.getCategory();
    	String text = message.getText();

    	if (StringUtils.isEmpty(title) || (title.matches("^(\\s|　)+$"))) {
            errorMessages.add("件名を入力してください");
        } else if (30 < title.length()) {
            errorMessages.add("件名は30文字以下で入力してください");
        }

    	if (StringUtils.isEmpty(category) || (category.matches("^(\\s|　)+$"))) {
            errorMessages.add("カテゴリを入力してください");
        } else if (10 < category.length()) {
            errorMessages.add("カテゴリは10文字以下で入力してください");
        }

        if (StringUtils.isEmpty(text) || (text.matches("^(\\s|　)+$"))) {
            errorMessages.add("投稿内容を入力してください");
        } else if (1000 < text.length()) {
            errorMessages.add("投稿内容は1000文字以下で入力してください");
        }

        if (errorMessages.size() == 0) {
            return true;
        }
        return false;
    }
}

src/controller/SettingServlet.java
package controller;

import java.io.IOException;
import java.util.ArrayList;
import java.util.List;

import javax.servlet.ServletException;
import javax.servlet.annotation.WebServlet;
import javax.servlet.http.HttpServlet;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import javax.servlet.http.HttpSession;

import org.apache.commons.lang.StringUtils;

import beans.Branch;
import beans.Department;
import beans.User;
import service.BranchService;
import service.DepartmentService;
import service.UserService;

@WebServlet(urlPatterns = { "/setting" })
public class SettingServlet extends HttpServlet {

	@Override
    protected void doGet(HttpServletRequest request, HttpServletResponse response)
            throws IOException, ServletException {

		String errorMessage = "不正なパラメータが入力されました";
		HttpSession session = request.getSession();

		String userInfId = request.getParameter("userInformationId");
		if ((StringUtils.isEmpty(userInfId)) || (userInfId.matches("^\\D+$"))) {
			session.setAttribute("errorMessage", errorMessage);
	    	response.sendRedirect("./management");
	    	return;
		}

	    int userInformationId = Integer.parseInt(userInfId);

	    //編集対象ユーザー取得
	    User user = new UserService().select(userInformationId);

	    if (user == null) {
	    	session.setAttribute("errorMessage", errorMessage);
	    	response.sendRedirect("./management");
	    	return;
	    }

	    //編集対象ユーザーをリクエストにセット
	    request.setAttribute("editUser", user);

	    //支社取得
  		List<Branch> branches = new BranchService().select();
  		//支社をリクエストにセット
  		request.setAttribute("branches", branches);

  		//部署取得
  		List<Department> departments = new DepartmentService().select();
  		//部署をリクエストにセット
  	    request.setAttribute("departments", departments);
        request.getRequestDispatcher("setting.jsp").forward(request, response);
    }

	@Override
	protected void doPost(HttpServletRequest request, HttpServletResponse response)
	        throws IOException, ServletException{

		List<String> errorMessages = new ArrayList<String>();

		User user = getUser(request);
		String checkPassword = request.getParameter("checkPassword");
		if (!isValid(user, errorMessages, checkPassword)) {
			request.setAttribute("errorMessages", errorMessages);
            request.setAttribute("errorEditUser", user);

            List<Branch> branches = new BranchService().select();
            request.setAttribute("branches", branches);
            List<Department> departments = new DepartmentService().select();
            request.setAttribute("departments", departments);

            request.getRequestDispatcher("setting.jsp").forward(request, response);
            return;
        }

		new UserService().update(user);
        response.sendRedirect("./management");
	}

	private User getUser(HttpServletRequest request) throws IOException, ServletException {

        User user = new User();
        user.setId(Integer.parseInt(request.getParameter("editUserId")));
        user.setAccount(request.getParameter("account"));
        user.setPassword(request.getParameter("password"));
        user.setName(request.getParameter("name"));
        user.setBranchId(Integer.parseInt(request.getParameter("branchId")));
        user.setDepartmentId(Integer.parseInt(request.getParameter("departmentId")));
        return user;
    }

    private boolean isValid(User user, List<String> errorMessages, String checkPassword) {

        String account = user.getAccount();
        String password = user.getPassword();
        String name = user.getName();
        int branchId = user.getBranchId();
        int departmentId = user.getDepartmentId();
        int id = user.getId();

        User checkUser = new UserService().select(id, account);

        if (StringUtils.isEmpty(account)) {
            errorMessages.add("アカウントを入力してください");
        } else if (account.length() < 6) {
        	errorMessages.add("アカウントは6文字以上で入力してください");
        } else if (20 < account.length()) {
            errorMessages.add("アカウントは20文字以下で入力してください");
        }

        if (StringUtils.isEmpty(password)) {
            errorMessages.add("パスワードを入力してください");
        } else if (! password.equals(checkPassword)) {
        	errorMessages.add("入力したパスワードと確認用パスワードが一致しません");
        }

        if ((! StringUtils.isEmpty(password)) && (password.length() < 6)) {
        	errorMessages.add("パスワードは6文字以上で入力してください");
        } else if (20 < password.length()) {
            errorMessages.add("パスワードは20文字以下で入力してください");
        }

        if (StringUtils.isEmpty(name)) {
            errorMessages.add("名前を入力してください");
        } else if (10 < name.length()) {
        	errorMessages.add("名前は10文字以下で入力してください");
        }

        if (checkUser != null) {
        	errorMessages.add("アカウントが重複しています");
        }

        if ((branchId == 1 && departmentId == 3) ||
        		(branchId == 1 && departmentId == 4) ||
        		(branchId == 2 && departmentId == 1) ||
        		(branchId == 2 && departmentId == 2) ||
        		(branchId == 3 && departmentId == 1) ||
        		(branchId == 3 && departmentId == 2) ||
        		(branchId == 4 && departmentId == 1) ||
        		(branchId == 4 && departmentId == 2)) {
        	errorMessages.add("支社と部署の組み合わせが不正です");
        }

        if (errorMessages.size() == 0) {
            return true;
        }
        return false;
    }
}

WebContent/home.jsp
<%@ page language="java" contentType="text/html; charset=UTF-8"
    pageEncoding="UTF-8"%>
<%@page isELIgnored="false"%>
<%@taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core"%>
<%@taglib prefix="fmt" uri="http://java.sun.com/jsp/jstl/fmt"%>
<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<html>
	<head>
		<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
		<title>ホーム画面</title>
		<link href="./css/style.css" rel="stylesheet" type="text/css">
	</head>
	<body>
		<div class="main-contents">
            <div class="header">
                <a href="message">新規投稿</a>
                <c:if test="${loginUser.branchId==1 && loginUser.departmentId==1}">
                	<a href="management">ユーザー管理</a>
                </c:if>
                <a href="logout">ログアウト</a>
            </div>

			<c:if test="${ not empty errorMessage }">
			    <div class="errorMessage">
			        <ul>
		                <li><c:out value="${errorMessage}" />
			        </ul>
			    </div>
			    <c:remove var="errorMessage" scope="session" />
			</c:if>

            <div class="narrow-down">
            	<form action="./" method="get">
            		<label for="date">日付</label>
                	<input type="date" name="start" id="start" value="${start}" /> ～
                	<input type="date" name="end" id="end" value="${end}" /> <br />

                	<label for="category">カテゴリ</label>
                	<input type="text" name="category" id="category" value="${category}" />
                	<input type="submit" value="絞り込み">
            	</form>
            </div>

            <c:if test="${ not empty errorMessages }">
			    <div class="errorMessages">
			        <ul>
			            <c:forEach items="${errorMessages}" var="errorMessage">
			                <li><c:out value="${errorMessage}" />
			            </c:forEach>
			        </ul>
			    </div>
			    <c:remove var="errorMessages" scope="session" />
			</c:if>

            <div class="messages">
			    <c:forEach items="${messages}" var="message">
			    <div class="message-comment">
			        <div class="message">
		        		<div class="name"><c:out value="${message.name}" /></div>
						<div class="title"><c:out value="${message.title}" /></div>
			            <div class="category"><c:out value="${message.category}" /></div>
			            <div class="text">
			            	<c:forEach items="${message.splitedText}" var="s">
			            		<div><c:out value="${s}" /></div>
			            	</c:forEach>
			            </div>
			            <div class="date"><fmt:formatDate value="${message.createdDate}" pattern="yyyy/MM/dd HH:mm:ss" /></div>
			        </div>
			        <c:if test="${message.userId==loginUser.id}">
						<div class="message-delete">
							<form action="deleteMessage" method="post" onsubmit="return checkmessage()">
								<input type="hidden" name="messageId" value="${message.id}">
								<input type="submit" value="削除">
							</form>
							<script type="text/javascript">
								function checkmessage() {
									return confirm("投稿を削除しますか？");
								}
							</script>
						</div>
					</c:if>

					<div class="comments">
						<c:forEach items="${comments}" var="comment">
							<c:if test="${message.id==comment.messageId}">
								<div class="comment">
									<div class="name"><c:out value="${comment.name}" /></div>
									<div class="text">
										<c:forEach items="${comment.splitedText}" var="s">
											<div><c:out value="${s}" /></div>
										</c:forEach>
									</div>
									<div class="date"><fmt:formatDate value="${comment.createdDate}" pattern="yyyy/MM/dd HH:mm:ss" /></div>
								</div>
								<c:if test="${comment.userId==loginUser.id}">
									<div class="comment-delete">
										<form action="deleteComment" method="post" onsubmit="return checkcomment()">
											<input type="hidden" name="commentId" value="${comment.id}">
											<input type="submit" value="削除">
										</form>
										<script type="text/javascript">
											function checkcomment() {
												return confirm("コメントを削除しますか？");
											}
										</script>
									</div>
								</c:if>
							</c:if>
						</c:forEach>
					</div>

			        <div class="form-area">
				        <form action="comment" method="post">
				            コメント入力欄(500文字以内)<br />
				            <textarea name="text" cols="100" rows="5" class="tweet-box"></textarea>
				            <br />
				            <input type="hidden" name="messageId" value="${message.id}">
				            <input type="submit" value="コメント投稿">
				        </form>
					</div>
				</div>
			    </c:forEach>
			</div>

            <div class="copyright"> Copyright(c)Nakamura Masahiro</div>
        </div>
	</body>
</html>

WebContent/login.jsp
<%@ page language="java" contentType="text/html; charset=UTF-8"
    pageEncoding="UTF-8"%>
<%@page isELIgnored="false"%>
<%@taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core"%>
<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<html>
	<head>
		<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
		<title>ログイン画面</title>
		<link href="./css/style.css" rel="stylesheet" type="text/css">
	</head>
	<body>
		<div class="main-contents">

			<c:if test="${ not empty errorMessage }">
			    <div class="errorMessage">
			        <ul>
		                <li><c:out value="${errorMessage}" />
			        </ul>
			    </div>
			    <c:remove var="errorMessage" scope="session" />
			</c:if>

            <c:if test="${ not empty errorMessages }">
                <div class="errorMessages">
                    <ul>
                        <c:forEach items="${errorMessages}" var="errorMessage">
                            <li><c:out value="${errorMessage}" />
                        </c:forEach>
                    </ul>
                </div>
            </c:if>

            <form action="login" method="post"><br />
                <label for="account">アカウント</label>
                <input type="text" name="account" id="account" value="${account}"/> <br />

                <label for="password">パスワード</label>
                <input name="password" type="password" id="password"/> <br />

                <input type="submit" value="ログイン" /> <br />
            </form>

            <div class="copyright"> Copyright(c)Nakamura Masahiro</div>
        </div>
	</body>
</html>

WebContent/management.jsp
<%@ page language="java" contentType="text/html; charset=UTF-8"
    pageEncoding="UTF-8"%>
<%@page isELIgnored="false"%>
<%@taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core"%>
<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<html>
	<head>
		<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
		<title>ユーザー管理画面</title>
		<link href="./css/style.css" rel="stylesheet" type="text/css">
	</head>
	<body>
		<div class="main-contents">
            <div class="header">
                <a href="./">ホーム</a>
                <a href="signup">ユーザー新規登録</a>
            </div>

			<c:if test="${ not empty errorMessage }">
			    <div class="errorMessage">
			        <ul>
		                <li><c:out value="${errorMessage}" />
			        </ul>
			    </div>
			    <c:remove var="errorMessage" scope="session" />
			</c:if>

            <div class="user-informations">
            	<c:forEach items="${userInformations}" var="userInformation">
            	<div class="user-information-table">
            		<div class="user-information">
            			<div class="account"><c:out value="${userInformation.account}" /></div>
            			<div class="name"><c:out value="${userInformation.name}" /></div>
						<div class="branch-name"><c:out value="${userInformation.branchName}" /></div>
			            <div class="department-name"><c:out value="${userInformation.departmentName}" /></div>
			            <div class="is-stopped">
			            	<c:if test="${userInformation.isStopped==0}">
								<c:out value="稼働中" />
							</c:if>
			            	<c:if test="${userInformation.isStopped==1}">
								<c:out value="停止中" />
							</c:if>
			            </div>
            		</div>
            		<div class="setting">
						<form action="setting" method="get">
							<input type="hidden" name="userInformationId" value="${userInformation.id}">
							<input type="submit" value="編集">
						</form>
						<c:if test="${loginUser.id==userInformation.id}">
							<c:if test="${userInformation.isStopped==0}">
								<c:out value="停止" />
							</c:if>
							<c:if test="${userInformation.isStopped==1}">
								<c:out value="復活" />
							</c:if>
						</c:if>
						<c:if test="${loginUser.id!=userInformation.id}">
							<c:if test="${userInformation.isStopped==0}">
								<form action="stop" method="post" onsubmit="return checkisstoppedto1()">
									<input type="hidden" name="userInformationId" value="${userInformation.id}">
									<input type="hidden" name="userInformationIsStopped" value="${userInformation.isStopped}">
									<input type="submit" value="停止">
								</form>
								<script type="text/javascript">
									function checkisstoppedto1() {
										return confirm("ユーザーを停止させますか？");
									}
								</script>
							</c:if>
							<c:if test="${userInformation.isStopped==1}">
								<form action="stop" method="post" onsubmit="return checkisstoppedto0()">
									<input type="hidden" name="userInformationId" value="${userInformation.id}">
									<input type="hidden" name="userInformationIsStopped" value="${userInformation.isStopped}">
									<input type="submit" value="復活">
								</form>
								<script type="text/javascript">
									function checkisstoppedto0() {
										return confirm("ユーザーを復活させますか？");
									}
								</script>
							</c:if>
						</c:if>
					</div>
				</div>
            	</c:forEach>
            </div>

            <div class="copyright"> Copyright(c)Nakamura Masahiro</div>
		</div>
	</body>
</html>

WebContent/message.jsp
<%@ page language="java" contentType="text/html; charset=UTF-8"
    pageEncoding="UTF-8"%>
<%@page isELIgnored="false"%>
<%@taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core"%>
<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<html>
	<head>
		<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
		<title>新規投稿画面</title>
		<link href="./css/style.css" rel="stylesheet" type="text/css">
	</head>
	<body>
		<div class="main-contents">
			<div class="header">
                <a href="./">ホーム</a>
            </div>

            <c:if test="${ not empty errorMessages }">
                <div class="errorMessages">
                    <ul>
                        <c:forEach items="${errorMessages}" var="errorMessage">
                            <li><c:out value="${errorMessage}" />
                        </c:forEach>
                    </ul>
                </div>
            </c:if>

            <form action="message" method="post"><br />
                <label for="title">件名(30文字以内)</label>
                <input type="text" name="title" id="title" value="${title}"/> <br />

                <label for="category">カテゴリ(10文字以内)</label>
                <input type="text" name="category" id="category" value="${category}"/> <br />

				<label for="text">投稿内容(1000文字以内)</label>
        		<textarea name="text" cols="100" rows="10" id="text">${text}</textarea> <br />
                <input type="submit" value="投稿" /> <br />
            </form>

            <div class="copyright">Copyright(c)Nakamura Masahiro</div>
        </div>
	</body>
</html>

WebContent/signup.jsp
<%@ page language="java" contentType="text/html; charset=UTF-8"
    pageEncoding="UTF-8"%>
<%@page isELIgnored="false"%>
<%@taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core"%>
<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<html>
	<head>
		<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
		<title>ユーザー新規登録</title>
		<link href="./css/style.css" rel="stylesheet" type="text/css">
	</head>
	<body>
		<div class="main-contents">
			<div class="header">
                <a href="management">ユーザー管理</a>
            </div>

            <c:if test="${ not empty errorMessages }">
                <div class="errorMessages">
                    <ul>
                        <c:forEach items="${errorMessages}" var="errorMessage">
                            <li><c:out value="${errorMessage}" />
                        </c:forEach>
                    </ul>
                </div>
                <c:remove var="errorMessages" scope="session" />
            </c:if>

            <form action="signup" method="post"><br />
                <label for="account">アカウント</label>
                <input type="text" name="account" id="account" value="${errorAccount}" /> <br />
                <c:remove var="errorAccount" scope="session" />

                <label for="password">パスワード</label>
                <input name="password" type="password" id="password" /> <br />

				<label for="password">確認用パスワード</label>
                <input name="checkPassword" type="password" id="checkPassword" /> <br />

				<label for="name">名前</label>
                <input type="text" name="name" id="name" value="${errorName}" /> <br />
                <c:remove var="errorName" scope="session" />

                <label for="branchId">支社</label>
                <select name="branchId">
                	<c:forEach items="${branches}" var="branch">
                		<option value="${branch.id}" <c:if test="${branch.id==errorBranchId}">selected</c:if>>${branch.name}</option>
                	</c:forEach>
                </select> <br />
                <c:remove var="errorBranchId" scope="session" />

                <label for="departmentId">部署</label>
                <select name="departmentId">
                	<c:forEach items="${departments}" var="department">
                		<option value="${department.id}" <c:if test="${department.id==errorDepartmentId}">selected</c:if>>${department.name}</option>
                	</c:forEach>
                </select> <br />
                <c:remove var="errorDepartmentId" scope="session" />

                <input type="submit" value="登録" /> <br />
            </form>

            <div class="copyright">Copyright(c)Nakamura Masahiro</div>
        </div>
	</body>
</html>